# ...

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      # ... avvalgi qadamlar

      - name: Deploy Docker image to Contabo server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Eski konteynerni to'xtatish
            docker stop ${{ env.DOCKER_IMAGE_NAME }} || true
            docker rm ${{ env.DOCKER_IMAGE_NAME }} || true
            
            # Yangi imagenI tortib olish
            docker pull ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            
            # Yangi konteynerni ishga tushurish
            docker run -d \
              --name ${{ env.DOCKER_IMAGE_NAME }} \
              -e POSTGRES_HOST=${{ env.DATABASE_HOST }} \
              -e POSTGRES_USER=${{ env.DATABASE_USER }} \
              -e POSTGRES_PASSWORD=${{ env.DATABASE_PASSWORD }} \
              -p 80:8080 \  # Productionda 80-port
              --restart unless-stopped \
              ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}